// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA42XrPax8A2SblqroxrsdsDFq9AX9n6BQ',
    appId: '1:988681105147:web:fbffe10f9f0478e05cca5e',
    messagingSenderId: '988681105147',
    projectId: 'connection-example-bf4f7',
    authDomain: 'connection-example-bf4f7.firebaseapp.com',
    storageBucket: 'connection-example-bf4f7.firebasestorage.app',
    measurementId: 'G-EVQB82P0BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACH6SicwVICNiWBfXTLiOWKzg_JiW44Is',
    appId: '1:988681105147:android:dbb6cbac6c8952b25cca5e',
    messagingSenderId: '988681105147',
    projectId: 'connection-example-bf4f7',
    storageBucket: 'connection-example-bf4f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpScJEjnVU3TljDIukquAjFSSruLOLqc',
    appId: '1:988681105147:ios:dc521fd9a8c862035cca5e',
    messagingSenderId: '988681105147',
    projectId: 'connection-example-bf4f7',
    storageBucket: 'connection-example-bf4f7.firebasestorage.app',
    iosClientId: '988681105147-80dt0dctj90lkfaissaai0hijc3jle7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectionFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFpScJEjnVU3TljDIukquAjFSSruLOLqc',
    appId: '1:988681105147:ios:dc521fd9a8c862035cca5e',
    messagingSenderId: '988681105147',
    projectId: 'connection-example-bf4f7',
    storageBucket: 'connection-example-bf4f7.firebasestorage.app',
    iosClientId: '988681105147-80dt0dctj90lkfaissaai0hijc3jle7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectionFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA42XrPax8A2SblqroxrsdsDFq9AX9n6BQ',
    appId: '1:988681105147:web:50fde5692ca6343c5cca5e',
    messagingSenderId: '988681105147',
    projectId: 'connection-example-bf4f7',
    authDomain: 'connection-example-bf4f7.firebaseapp.com',
    storageBucket: 'connection-example-bf4f7.firebasestorage.app',
    measurementId: 'G-DELTD95HBZ',
  );
}
